"""文档类 Skill 的共用校验层。"""

from modules.skills.documents.drafting import (
    MAX_REWRITES,
    DraftResult,
    Usage,
    generate_skeleton,
    generate_with_review,
)
from modules.skills.documents.facts import (
    Fact,
    FactSheet,
    fact_sheet_from_analysis,
)
from modules.skills.documents.checks import (
    SEVERITY_ERROR,
    SEVERITY_INFO,
    SEVERITY_WARNING,
    TAG_ASSUMPTION,
    TAG_PENDING,
    TAG_TODO,
    TAGS,
    DocumentReview,
    Finding,
    check_assumptions_indexed,
    check_data_consistency,
    check_equations,
    check_heading_depth,
    check_percentage_totals,
    check_required_sections,
    check_table_totals,
    collect_tags,
    extract_heading_outline,
    headings,
    markdown_tables,
)

__all__ = [
    "MAX_REWRITES",
    "DraftResult",
    "Usage",
    "generate_skeleton",
    "generate_with_review",
    "Fact",
    "FactSheet",
    "fact_sheet_from_analysis",
    "SEVERITY_ERROR",
    "SEVERITY_INFO",
    "SEVERITY_WARNING",
    "TAGS",
    "TAG_ASSUMPTION",
    "TAG_PENDING",
    "TAG_TODO",
    "DocumentReview",
    "Finding",
    "check_assumptions_indexed",
    "check_data_consistency",
    "check_equations",
    "check_heading_depth",
    "check_percentage_totals",
    "check_required_sections",
    "check_table_totals",
    "collect_tags",
    "extract_heading_outline",
    "headings",
    "markdown_tables",
]
